-- USER SQL
CREATE USER GRAPHUSER IDENTIFIED BY "stored_in_keepass";

-- ADD ROLES
GRANT CONNECT TO GRAPHUSER;
GRANT CONSOLE_DEVELOPER TO GRAPHUSER;
GRANT GRAPH_DEVELOPER TO GRAPHUSER;
GRANT RESOURCE TO GRAPHUSER;
ALTER USER GRAPHUSER DEFAULT ROLE CONNECT,CONSOLE_DEVELOPER,GRAPH_DEVELOPER,RESOURCE;

-- REST ENABLE
BEGIN
    ORDS_ADMIN.ENABLE_SCHEMA(
        p_enabled => TRUE,
        p_schema => 'GRAPHUSER',
        p_url_mapping_type => 'BASE_PATH',
        p_url_mapping_pattern => 'graphuser',
        p_auto_rest_auth=> TRUE
    );
    -- ENABLE DATA SHARING
    C##ADP$SERVICE.DBMS_SHARE.ENABLE_SCHEMA(
            SCHEMA_NAME => 'GRAPHUSER',
            ENABLED => TRUE
    );
    commit;
END;
/

-- ENABLE GRAPH
ALTER USER GRAPHUSER GRANT CONNECT THROUGH GRAPH$PROXY_USER;

-- QUOTA
ALTER USER GRAPHUSER QUOTA UNLIMITED ON DATA;


-- GRANT SELECT ON OML_USER TABLES TO GRAPHUSER
-- Run these connected as ADMIN (OML_USER. prefix makes them schema-qualified).

-- Olist tables
GRANT SELECT ON OML_USER.CUSTOMERS                    TO GRAPHUSER;
GRANT SELECT ON OML_USER.ORDERS                       TO GRAPHUSER;
GRANT SELECT ON OML_USER.ORDER_ITEMS                  TO GRAPHUSER;
GRANT SELECT ON OML_USER.ORDER_PAYMENTS               TO GRAPHUSER;
GRANT SELECT ON OML_USER.ORDER_REVIEWS                TO GRAPHUSER;
GRANT SELECT ON OML_USER.PRODUCTS                     TO GRAPHUSER;
GRANT SELECT ON OML_USER.PRODUCT_CATEGORY_TRANSLATION TO GRAPHUSER;
GRANT SELECT ON OML_USER.SELLERS                      TO GRAPHUSER;
GRANT SELECT ON OML_USER.GEOLOCATION                  TO GRAPHUSER;

-- Cardiotocography
GRANT SELECT ON OML_USER.CARDIOTOCOGRAPHY             TO GRAPHUSER;

-- Synthea tables (run as ADMIN)
GRANT SELECT ON OML_USER.SYN_PATIENTS              TO GRAPHUSER;
GRANT SELECT ON OML_USER.SYN_ENCOUNTERS            TO GRAPHUSER;
GRANT SELECT ON OML_USER.SYN_PAYER_TRANSITIONS     TO GRAPHUSER;
GRANT SELECT ON OML_USER.SYN_CONDITIONS            TO GRAPHUSER;
GRANT SELECT ON OML_USER.SYN_MEDICATIONS           TO GRAPHUSER;
GRANT SELECT ON OML_USER.SYN_PROCEDURES            TO GRAPHUSER;
GRANT SELECT ON OML_USER.SYN_OBSERVATIONS          TO GRAPHUSER;
GRANT SELECT ON OML_USER.SYN_CLAIMS                TO GRAPHUSER;
GRANT SELECT ON OML_USER.SYN_CLAIMS_TRANSACTIONS   TO GRAPHUSER;
GRANT SELECT ON OML_USER.SYN_IMMUNIZATIONS         TO GRAPHUSER;
GRANT SELECT ON OML_USER.SYN_ALLERGIES             TO GRAPHUSER;
GRANT SELECT ON OML_USER.SYN_CAREPLANS             TO GRAPHUSER;
GRANT SELECT ON OML_USER.SYN_DEVICES               TO GRAPHUSER;

select * from dba_role_privs where grantee='GRAPHUSER';

select * from dba_proxies where client='GRAPHUSER';
